-- Initial production data snapshot. This applied migration is immutable.
PRAGMA foreign_keys = ON;
DELETE FROM recipe_tags;
DELETE FROM recipe_steps;
DELETE FROM recipe_ingredients;
DELETE FROM recipes;
DELETE FROM ingredient_aliases;
DELETE FROM ingredients;
INSERT INTO ingredients (id, name, normalized_name) VALUES ('amaretto', 'amaretto', 'amaretto');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('amaretto', 'amaretta', 'amaretta');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('cesnek', 'česnek', 'cesnek');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('cesnek', 'česneku', 'cesneku');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('chleba', 'chléb', 'chleb');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('chleba', 'chleba', 'chleba');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('cuketa', 'cuketa', 'cuketa');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('cuketa', 'střední cuketa', 'stredni cuketa');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('cukr', 'cukr', 'cukr');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('cukr', 'třtinového cukru', 'trtinoveho cukru');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('cukr-krupice', 'krupicový cukr', 'krupicovy cukr');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('cukr-krupice', 'krupicového cukru', 'krupicoveho cukru');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('cukrarske-piskoty', 'cukrářské piškoty', 'cukrarske piskoty');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('cukrarske-piskoty', 'cukrářských piškotů', 'cukrarskych piskotu');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('cedar', 'čedar', 'cedar');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('cedar', 'čedaru', 'cedaru');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('cokolada', 'čokoláda', 'cokolada');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('cokolada', 'hořké čokolády', 'horke cokolady');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('hrasek', 'hrášek', 'hrasek');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('hrasek', 'mraženého hrášku', 'mrazeneho hrasku');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('jogurt', 'jogurt', 'jogurt');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('jogurt', 'bílého jogurtu', 'bileho jogurtu');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('kakao', 'kakao', 'kakao');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('kakao', 'kakaa', 'kakaa');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('kava', 'káva', 'kava');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('kava', 'zrnkové mleté kávy', 'zrnkove mlete kavy');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('kureci-bujon', 'kuřecí bujón', 'kureci bujon');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('mascarpone', 'mascarpone', 'mascarpone');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('maslo', 'máslo', 'maslo');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('mouka', 'hladká mouka', 'hladka mouka');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('mouka', 'mouka', 'mouka');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('mouka', 'hladké mouky', 'hladke mouky');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('mouka', 'celozrnné hladké mouky', 'celozrnne hladke mouky');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('parmezan', 'parmezán', 'parmezan');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('parmezan', 'parmezánu', 'parmezanu');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('pepr', 'pepř', 'pepr');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('pepr', 'pepře', 'pepre');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('pepr', 'čerstvě namletého pepře', 'cerstve namleteho pepre');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('prasek-do-peciva', 'prášek do pečiva', 'prasek do peciva');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('ryze-arborio', 'rýže Arborio', 'ryze arborio');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('slanina', 'slanina', 'slanina');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('slanina', 'slaniny', 'slaniny');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('spagety', 'špagety', 'spagety');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('spagety', 'špaget', 'spaget');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('sul', 'sůl', 'sul');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('sul', 'soli', 'soli');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('susena-petrzel', 'sušená petržel', 'susena petrzel');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('susena-petrzel', 'sušené petrželky', 'susene petrzelky');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('susene-houby', 'sušené houby', 'susene houby');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('susene-houby', 'sušených hub', 'susenych hub');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('salotka', 'šalotka', 'salotka');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('tymian', 'tymián', 'tymian');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('tymian', 'sušeneho tymiánu', 'suseneho tymianu');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('vejce', 'vejce', 'vejce');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('visne', 'višně', 'visne');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('visne', 'višeň', 'visen');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('visne', 'višní', 'visni');
INSERT INTO ingredients (id, name, normalized_name) VALUES ('zampiony', 'žampiony', 'zampiony');
INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES ('zampiony', 'žampionů', 'zampionu');
INSERT INTO recipes (id, title, description, draft, category, published, image_key, image_alt, serves, minutes, difficulty) VALUES ('73lwR7JKHA4QzyIl2P2E', 'Tiramisu', 'Italský klasický dezert, který zažene špatnou náladu.', 0, 'dezerty', '2020-01-12', 'recipes/73lwR7JKHA4QzyIl2P2E-main.jpg', 'Tiramisu – hotový pokrm', 4, 20, 'Snadné');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('73lwR7JKHA4QzyIl2P2E', 0, 'amaretto', 'amaretta', 5, 'cl');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('73lwR7JKHA4QzyIl2P2E', 1, 'cukr-krupice', 'krupicového cukru', 2, 'lžíce');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('73lwR7JKHA4QzyIl2P2E', 2, 'kakao', 'kakaa', 1, 'lžíce');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('73lwR7JKHA4QzyIl2P2E', 3, 'kava', 'zrnkové mleté kávy', 1, 'lžička');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('73lwR7JKHA4QzyIl2P2E', 4, 'vejce', 'vejce', 2, '');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('73lwR7JKHA4QzyIl2P2E', 5, 'cukrarske-piskoty', 'cukrářských piškotů', 12, '');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('73lwR7JKHA4QzyIl2P2E', 6, 'mascarpone', 'mascarpone', 250, 'g');
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('73lwR7JKHA4QzyIl2P2E', 0, 'Uvaříme si malý hrnek kávy a přidáme do něj amaretto.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('73lwR7JKHA4QzyIl2P2E', 1, 'Žloutky si vyšleháme s cukrem, poté zašleháme mascarpone a nakonec zlehka vmícháme ušlehaný sníh z bílků.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('73lwR7JKHA4QzyIl2P2E', 2, 'Připravíme si čtyři nízké skleničky. A namáčíme piškoty do kávy s likérem tak, aby nasákly tekutinu, ale nebyly příliš rozmočené a vložíme je na dno skleniček. Na piškoty rozetřeme polovinu krému a na krém opět namočené piškoty a další vrstvu krému, kterou posypeme kakaem.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('73lwR7JKHA4QzyIl2P2E', 3, 'Skleničky uložíme aspoň na 2 hodiny do lednice.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('73lwR7JKHA4QzyIl2P2E', 4, 'Recept obsahuje syrová vejce, proto je dobré mít vejce co nejčerstvější.', 1, NULL, NULL);
INSERT INTO recipe_tags (recipe_id, tag) VALUES ('73lwR7JKHA4QzyIl2P2E', 'Itálie');
INSERT INTO recipes (id, title, description, draft, category, published, image_key, image_alt, serves, minutes, difficulty) VALUES ('7uDf27jmYF8R2AjVwqfR', 'Krutonky', 'Krutonky si můžeme vyrobit z jakéhokoliv pečiva, které máme rádi, nejlépe den dva starého, prostě z toho, které nám zbylo. Někdo má rád krutonky v polévce jen na ozdobu a někdo jich sní celou misku. A tím se stane z polévky hlavní chod.', 0, 'dezerty', '2018-02-20', 'recipes/7uDf27jmYF8R2AjVwqfR-main.jpg', 'Krutonky – hotový pokrm', 2, 15, 'Snadné');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('7uDf27jmYF8R2AjVwqfR', 0, 'chleba', 'chleba', 4, 'krajíce');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('7uDf27jmYF8R2AjVwqfR', 1, 'cesnek', 'česneku', 1, 'stroužek');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('7uDf27jmYF8R2AjVwqfR', 2, 'susena-petrzel', 'sušené petrželky', 1, 'lžička');
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('7uDf27jmYF8R2AjVwqfR', 0, 'Krutonky můžeme připravit dopředu a schovat do suché vzduchotěsné nádoby.', 1, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('7uDf27jmYF8R2AjVwqfR', 1, 'Pečivo pokrájíme na středně velké kostičky.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('7uDf27jmYF8R2AjVwqfR', 2, 'Osmahneme na středně rozpálené grilovací nebo obyčejné pánvi na sucho spolu se stroužkem česneku, který jsme neoloupali a sušenou petrželkou. Průběžně prohazujeme/promícháváme.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('7uDf27jmYF8R2AjVwqfR', 3, 'Krutonky lze také upéct v troubě (190°, 10min), kde dojde k rovnoměrnému opečení a stačí promíchat jen jednou, v polovině době pečení.', 1, NULL, NULL);
INSERT INTO recipe_tags (recipe_id, tag) VALUES ('7uDf27jmYF8R2AjVwqfR', 'bio');
INSERT INTO recipe_tags (recipe_id, tag) VALUES ('7uDf27jmYF8R2AjVwqfR', 'light');
INSERT INTO recipes (id, title, description, draft, category, published, image_key, image_alt, serves, minutes, difficulty) VALUES ('Kd202PmJmbCufFELxLCA', 'Italské houbové rizoto', 'Krémové italské rizoto pro chmurné dny.', 0, 'dezerty', '2018-02-17', 'recipes/Kd202PmJmbCufFELxLCA-main.jpg', 'Italské houbové rizoto – hotový pokrm', 4, 50, 'Snadné');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('Kd202PmJmbCufFELxLCA', 0, 'zampiony', 'žampionů', 250, 'g');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('Kd202PmJmbCufFELxLCA', 1, 'salotka', 'šalotka', 1, '');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('Kd202PmJmbCufFELxLCA', 2, 'sul', 'soli', 1, 'spetka');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('Kd202PmJmbCufFELxLCA', 3, 'hrasek', 'mraženého hrášku', 150, 'g');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('Kd202PmJmbCufFELxLCA', 4, 'ryze-arborio', 'rýže Arborio', 340, 'g');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('Kd202PmJmbCufFELxLCA', 5, 'kureci-bujon', 'kuřecí bujón', 1, '');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('Kd202PmJmbCufFELxLCA', 6, 'parmezan', 'parmezánu', 150, 'g');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('Kd202PmJmbCufFELxLCA', 7, 'pepr', 'pepře', 1, 'spetka');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('Kd202PmJmbCufFELxLCA', 8, 'cuketa', 'střední cuketa', 1, '');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('Kd202PmJmbCufFELxLCA', 9, 'susene-houby', 'sušených hub', 0.5, 'hrnku');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('Kd202PmJmbCufFELxLCA', 10, 'tymian', 'sušeneho tymiánu', 1, 'lzicka');
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('Kd202PmJmbCufFELxLCA', 0, 'Sušené houby namočíme do teplé vody. A na troše olivového oleje osmahneme omyté a nakrájené žampiony a šalotku nakrájenou na jemno.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('Kd202PmJmbCufFELxLCA', 1, 'Cuketu zbavíme slupky, nakrájíme na malé kostičky a přidáme do pánve, osolíme, opepříme a okořeníme tymiánem.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('Kd202PmJmbCufFELxLCA', 2, 'Dále přidáme rýži a promícháme. Vhodíme bujón a 2 hrnky vody. Vodu přidáváme postupně (celkem cca 1l). Do pánve přilijeme i vodu ze sušených hub a přidáme sušené houby.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('Kd202PmJmbCufFELxLCA', 3, 'Ke konci vaření přidáme mražený hrášek. Poté parmezán a ještě lehce prohřejeme, ale už nevaříme.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('Kd202PmJmbCufFELxLCA', 4, 'Ihned podáváme posypané parmezánem.', 0, NULL, NULL);
INSERT INTO recipe_tags (recipe_id, tag) VALUES ('Kd202PmJmbCufFELxLCA', 'bio');
INSERT INTO recipes (id, title, description, draft, category, published, image_key, image_alt, serves, minutes, difficulty) VALUES ('ZcWqZjnIW81zafRQ41DG', 'Salát se sýrem brie', 'Jemný sýr brie v kombinaci s lehce kyselými jablky, křupavými ořechy, čerstvým salátem a medovou zálivkou je ideální na rychlý oběd.', 1, 'saláty', '2020-01-27', 'recipes/ZcWqZjnIW81zafRQ41DG-main.jpg', 'Salát se sýrem brie – hotový pokrm', 2, 15, 'Snadné');
INSERT INTO recipes (id, title, description, draft, category, published, image_key, image_alt, serves, minutes, difficulty) VALUES ('gSdIeyNxhVffc2aO2cAf', 'Perník s meruňkovou marmeládou', 'Vůně perníkového koření provoní domov a v kombinaci s meruňkovou marmeládou je perník ideální k odpolední kávě či čaji.', 1, 'dezerty', '2020-04-04', 'recipes/gSdIeyNxhVffc2aO2cAf-main.jpg', 'Perník s meruňkovou marmeládou – hotový pokrm', 24, 60, 'Snadné');
INSERT INTO recipes (id, title, description, draft, category, published, image_key, image_alt, serves, minutes, difficulty) VALUES ('jpscnE6PuIduHCLLdJnU', 'Špagety Carbonara', 'Italská klasika, která nikdy nezklame.', 0, 'hlavní chody', '2020-01-12', 'recipes/jpscnE6PuIduHCLLdJnU-main.jpg', 'Špagety Carbonara – hotový pokrm', 4, 20, 'Snadné');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('jpscnE6PuIduHCLLdJnU', 0, 'slanina', 'slaniny', 150, 'g');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('jpscnE6PuIduHCLLdJnU', 1, 'spagety', 'špaget', 500, 'g');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('jpscnE6PuIduHCLLdJnU', 2, 'sul', 'soli', NULL, 'špetka');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('jpscnE6PuIduHCLLdJnU', 3, 'pepr', 'čerstvě namletého pepře', NULL, 'lžička');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('jpscnE6PuIduHCLLdJnU', 4, 'vejce', 'vejce', 4, '');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('jpscnE6PuIduHCLLdJnU', 5, 'cedar', 'čedaru', 150, 'g');
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('jpscnE6PuIduHCLLdJnU', 0, 'Dáme vařit vodu na špagety. A mezitím si orestujeme slaninu nakrájenou na kostičky na troše olivového oleje.', 0, 'recipes/jpscnE6PuIduHCLLdJnU-step-1.jpg', 'Špagety Carbonara – postup, krok 1');
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('jpscnE6PuIduHCLLdJnU', 1, 'Dáme vařit špagety. Do misky si nastrouháme čedar a čtvrtinu si odložíme stranou. K sýru přidáme rozklepnutá vejce, pepř, trochu soli a rozmícháme.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('jpscnE6PuIduHCLLdJnU', 2, 'Uvařené špagety slijeme, ale necháme si hrnek vody stranou. Ke špagetám přidáme směs vajec a sýru a polovinu hrnku vody. Mícháním se vytvoří lehká omáčka, která obalí špagety. Podle konzistence případně přilijeme ještě vodu ze špaget.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('jpscnE6PuIduHCLLdJnU', 3, 'Dále přidáme slaninu, zamícháme a ihned podáváme posypané zbylým čedarem.', 0, NULL, NULL);
INSERT INTO recipe_tags (recipe_id, tag) VALUES ('jpscnE6PuIduHCLLdJnU', 'Itálie');
INSERT INTO recipes (id, title, description, draft, category, published, image_key, image_alt, serves, minutes, difficulty) VALUES ('mmRswzC4uecNEoia0MH6', 'Čokoládové muffiny s višněmi', 'Neodolatelná kombinace čokolády a višní.', 0, 'dezerty', '2018-02-25', 'recipes/mmRswzC4uecNEoia0MH6-main.jpg', 'Čokoládové muffiny s višněmi – hotový pokrm', 12, 50, 'Snadné');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('mmRswzC4uecNEoia0MH6', 0, 'prasek-do-peciva', 'prášek do pečiva', 1, '');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('mmRswzC4uecNEoia0MH6', 1, 'mouka', 'celozrnné hladké mouky', 1, 'hrnek');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('mmRswzC4uecNEoia0MH6', 2, 'cokolada', 'hořké čokolády', 200, 'g');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('mmRswzC4uecNEoia0MH6', 3, 'jogurt', 'bílého jogurtu', 150, 'g');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('mmRswzC4uecNEoia0MH6', 4, 'kakao', 'kakaa', 2, 'lžíce');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('mmRswzC4uecNEoia0MH6', 5, 'vejce', 'vejce', 2, '');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('mmRswzC4uecNEoia0MH6', 6, 'visne', 'višní', 200, 'g');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('mmRswzC4uecNEoia0MH6', 7, 'maslo', 'máslo', 100, 'g');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('mmRswzC4uecNEoia0MH6', 8, 'mouka', 'hladké mouky', 1, 'hrnek');
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES ('mmRswzC4uecNEoia0MH6', 9, 'cukr', 'třtinového cukru', NULL, 'hrnku');
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('mmRswzC4uecNEoia0MH6', 0, 'Na vodní lázni si rozpustíme 120g čokolády s máslem.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('mmRswzC4uecNEoia0MH6', 1, 'Čokoládu a máslo můžeme rozpustit i v mikrovlnce. Dáme ho do ní na 30s, vyndáme, zamícháme a znovu ho tam vložíme na 20s a podle potřeby opakujeme, dokud není čokoláda s máslem rozpuštěná. Dáváme pozor, aby se nám čokoláda nespálila.', 1, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('mmRswzC4uecNEoia0MH6', 2, 'Troubu si předehřejeme na 200°C.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('mmRswzC4uecNEoia0MH6', 3, 'Nejdříve si v míse smícháme mouku, cukr, prášek do pečiva a kakao, uděláme důlek a přidáme jogurt, vejce a vychladlou rozpuštěnou čokoládu s máslem.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('mmRswzC4uecNEoia0MH6', 4, 'Nakonec zlehka vmícháme vypeckované višně a zbytek čokolády pokrájené na kousky.', 0, NULL, NULL);
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('mmRswzC4uecNEoia0MH6', 5, 'Směsí naplníme muffinovou formu vyloženou papírovými košíčky.', 0, 'recipes/mmRswzC4uecNEoia0MH6-step-6.jpg', 'Čokoládové muffiny s višněmi – postup, krok 6');
INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES ('mmRswzC4uecNEoia0MH6', 6, 'Pečeme 30min na 180°C.', 0, NULL, NULL);
INSERT INTO recipe_tags (recipe_id, tag) VALUES ('mmRswzC4uecNEoia0MH6', 'čokoláda');
