import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, dirname } from 'node:path';

const output = process.argv[2] ?? 'database/seed.sql';
const catalog = JSON.parse(await readFile('src/data/ingredients.json', 'utf8'));
const recipeFiles = (await readdir('src/content/recipes')).filter(name => name.endsWith('.json')).sort();
const recipes = await Promise.all(recipeFiles.map(async name => ({
  id: name.replace(/\.json$/, ''),
  ...JSON.parse(await readFile(`src/content/recipes/${name}`, 'utf8')),
})));

const quote = value => value == null ? 'NULL' : `'${String(value).replaceAll("'", "''")}'`;
const number = value => value == null ? 'NULL' : String(value);
const normalize = value => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('cs').trim();
const imageKey = value => value ? `recipes/${basename(value)}` : null;
const statements = [
  '-- Generated by npm run db:generate-seed. Do not edit by hand.',
  'PRAGMA foreign_keys = ON;',
  'DELETE FROM recipe_tags;',
  'DELETE FROM recipe_steps;',
  'DELETE FROM recipe_ingredients;',
  'DELETE FROM recipes;',
  'DELETE FROM ingredient_aliases;',
  'DELETE FROM ingredients;',
];

for (const ingredient of catalog) {
  statements.push(`INSERT INTO ingredients (id, name, normalized_name) VALUES (${quote(ingredient.id)}, ${quote(ingredient.name)}, ${quote(normalize(ingredient.name))});`);
  for (const alias of ingredient.aliases) {
    statements.push(`INSERT INTO ingredient_aliases (ingredient_id, alias, normalized_alias) VALUES (${quote(ingredient.id)}, ${quote(alias)}, ${quote(normalize(alias))});`);
  }
}

for (const recipe of recipes) {
  statements.push(`INSERT INTO recipes (id, title, description, draft, category, published, image_key, image_alt, serves, minutes, difficulty) VALUES (${quote(recipe.id)}, ${quote(recipe.title)}, ${quote(recipe.description)}, ${recipe.draft ? 1 : 0}, ${quote(recipe.category)}, ${quote(recipe.published)}, ${quote(imageKey(recipe.photo))}, ${quote(recipe.photoAlt)}, ${recipe.serves}, ${recipe.minutes}, ${quote(recipe.difficulty)});`);
  recipe.ingredients.forEach((ingredient, position) => statements.push(`INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, display_name, quantity, unit) VALUES (${quote(recipe.id)}, ${position}, ${quote(ingredient.ingredientId)}, ${quote(ingredient.name)}, ${number(ingredient.quantity)}, ${quote(ingredient.unit)});`));
  recipe.steps.forEach((step, position) => statements.push(`INSERT INTO recipe_steps (recipe_id, position, content, tip, image_key, image_alt) VALUES (${quote(recipe.id)}, ${position}, ${quote(step.content)}, ${step.tip ? 1 : 0}, ${quote(imageKey(step.photo))}, ${quote(step.photoAlt)});`));
  recipe.tags.forEach(tag => statements.push(`INSERT INTO recipe_tags (recipe_id, tag) VALUES (${quote(recipe.id)}, ${quote(tag)});`));
}

statements.push('');
await mkdir(dirname(output), { recursive: true });
await writeFile(output, statements.join('\n'));
console.log(`Generated ${output} with ${catalog.length} ingredients and ${recipes.length} recipes.`);
